# Generated by Django 5.2.15 on 2026-07-05 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='assigned_contractors',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_contractor',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('pm', 'Project Manager'), ('engineer', 'Engineer')], default='engineer', max_length=20),
        ),
    ]
