# Generated by Django 5.2.15 on 2026-07-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_notification_related_project_project_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='project_files/'),
        ),
    ]
