# Generated by Django 5.2.15 on 2026-07-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
