# Generated by Django 6.0.6 on 2026-07-06 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_user_notification_recipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('pm', 'Project Manager'), ('engineer', 'Engineer'), ('client', 'Client'), ('unassigned', 'Unassigned')], default='unassigned', max_length=20),
        ),
    ]
